GROQ_API_KEY = "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"
SUPABASE_URL = "https://ymwdvqmfblnewoiicpkk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltd2R2cW1mYmxuZXdvaWljcGtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk1OTQwNDUsImV4cCI6MjA4NTE3MDA0NX0.pYML1VPXRrehBlx6qnf9sWTrQ_gdiLLZ7FaQksLMpzY"
ADMIN_PASSWORD = "TUDAL"


